### ISSUE TITLE
Make Webpage mobile responsive

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#1]
The task assigned to this issue is to make this web page responsive on mobile devices without compromising any animations or performance. This can be done with relative ease and is a beginner-friendly issue. 

_Please comment below and assign this to yourself before starting to work on it._

**Comment by Chavda-Mitul** [comment]
assign this to me

**Comment by Chavda-Mitul** [comment]
assign this to me

**Comment by avincodes** [comment]
Done, Thank You!

**Comment by JagroopNatt** [comment]
Is it still open 
if yes please assign to me

**Comment by avincodes** [comment]
@Chavda-Mitul I will be assigning this to @JagroopNatt due to inactivity!

**Comment by Aditi-1709** [comment]
Is this issue still open ?

**Comment by avincodes** [comment]
@Aditi-1709 yes you can go for it! Please confirm!

**Comment by avincodes** [comment]
Any updates here @Aditi-1709
