### ISSUE TITLE
Change Content

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#12]
The task related to the issue is to change the following content from ```kydzs#0497``` to ```Yep, I mean it!``` in the section shown on the screenshot below!
![image](https://user-images.githubusercontent.com/66766682/194766706-e09b5084-cfeb-4caf-8ce9-2a7e154a01ea.png)

**Comment by kiran-thilak** [comment]
Can i work on this issue?

**Comment by sunny7899** [comment]
i am working on this

**Comment by Tiansing** [comment]
I can work with this in a fantastic way

**Comment by avincodes** [comment]
@sunny7899 already fixed this issue, @Tiansing you can look at the other issues! Thank you!
