### ISSUE TITLE
Make a Cool Header!

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#13]
The task related to this issue is to make a header file that fits the repository incorporating the name and the design! You are free to get creative and explore! Please note that you might need to revise and make changes as per the maintainer's requests!

**Comment by MuzhdaN** [comment]
Hi, 
I would like to work on this if no one has taken it.

Also, do you have any preferred designs for the header?

**Comment by avincodes** [comment]
You can have it @MuzhdaN, and no, but if you have any please run them by me before you start! Thank you!

**Comment by MuzhdaN** [comment]
Do you have a logo? or `Avin.here()` is a logo?

**Comment by curator69** [comment]
do let me know if any help needed here

**Comment by avincodes** [comment]
No @MuzhdaN I think you have misunderstood! I want a header for the readme of the repo!

**Comment by pedroagcf** [comment]
just let me know if you need some help with the documentation guys @avincodes @MuzhdaN

**Comment by avincodes** [comment]
@pedroagcf can you take up this issue?

**Comment by whizzbbig** [comment]
> @pedroagcf can you take up this issue?

I can take up this issue can you describe more thorough like sharing the ss of how more likely you want it to be look like

**Comment by avincodes** [comment]
@whizzbbig you can be create, what I need is a image for the header to be used the repo readme file!

**Comment by whizzbbig** [comment]
yep assign me till then i'll come with a design

**Comment by whizzbbig** [comment]
@avincodes this is what i made for moodboards
here i want you to suggest me something that you might like to add here 
whether in terms of graphics textures or somethings you might like
![Frame 2](https://user-images.githubusercontent.com/54703305/196028356-5b03c83f-a9db-4d1b-bcfe-373e10c99922.png)
also can you express more so i can get what more i can do to not only make it look good but also make it same with whole website

**Comment by avincodes** [comment]
Yeah is it possible to add the theme of the website, the color combo and the GitHub logo too maybe?

**Comment by whizzbbig** [comment]
> Yeah is it possible to add the theme of the website, the color combo and the GitHub logo too maybe?

yeah it is possible this is the background that i think would be in place of that empty bland background

**Comment by avincodes** [comment]
Oh yeah sure add the stuff on top of this!

**Comment by whizzbbig** [comment]
> Oh yeah sure add the stuff on top of this!

okay i'll PR it till then can you please assign me this?
