### ISSUE TITLE
Make a Book a call page

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#19]
The tasks related to this issue are

- [x] Create a "Book a Call" Page
- [x] Make Sure it follows the general design guidelines of the website
- [x] #26
- [ ] Link Page to Site Header

Please get this issue assigned to yourself before you start working on it!

**Comment by VANSHAJB10** [comment]
please assign me this @avincodes

**Comment by avincodes** [comment]
Go for it @VANSHAJB10! If you are contributing to hacktoberfest, I will let you submit the work in two pull requests since this is a lot of work (If you want to, ofc!) Thank you!

**Comment by VANSHAJB10** [comment]
thank you @avincodes 
so, I will submit it in 2 pull requests

**Comment by avincodes** [comment]
For sure @VANSHAJB10!!

**Comment by avincodes** [comment]
Any update @VANSHAJB10

**Comment by VANSHAJB10** [comment]
Will do this by this Wednesday or Thursday for sure!

**Comment by avincodes** [comment]
Sure thank you! @VANSHAJB10

**Comment by VANSHAJB10** [comment]
working on it ... stick in some CSS elements

**Comment by avincodes** [comment]
Do you have a date by when you can give it? Not to push you! Also attach your adress when maing the PR, I have a small suprise for you! 😉

**Comment by VANSHAJB10** [comment]
Page is ready.
Please share your calendly link.

**Comment by VANSHAJB10** [comment]
> Do you have a date by when you can give it? Not to push you! Also attach your address (If you're comfortable) when making the PR, I have a small Suprise for you! 😉

Which address are you talking about?
email address? or my home address?

**Comment by avincodes** [comment]
You can embed the following code: 
```
<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/avinhere/30min?hide_gdpr_banner=1" style="min-width:320px;height:700px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->
```

**Comment by avincodes** [comment]
> > Do you have a date by when you can give it? Not to push you! Also attach your address (If you're comfortable) when making the PR, I have a small Suprise for you! 😉
> 
> Which address are you talking about? email address? or my home address?

A postal address to send you some stickers! Once again, only if you're comfortable and interested!

**Comment by VANSHAJB10** [comment]
> > > Do you have a date by when you can give it? Not to push you! Also attach your address (If you're comfortable) when making the PR, I have a small Suprise for you! 😉
> > 
> > 
> > Which address are you talking about? email address? or my home address?
> 
> A postal address to send you some stickers! Once again, only if you're comfortable and interested!

Kindly check your Twitter ... Dmed you there

**Comment by VANSHAJB10** [comment]
> You can embed the following code:
> 
> ```
> 
> <div class="calendly-inline-widget" data-url="https://calendly.com/avinhere/30min?hide_gdpr_banner=1" style="min-width:320px;height:700px;"></div>
> <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
> 
> ```

Okay

**Comment by VANSHAJB10** [comment]
Raised a PR ✅

**Comment by manish-bhukar** [comment]
Assign this to me if remaining tasks to be complete.@avincodes

**Comment by avincodes** [comment]
Hi @manish-bhukar @VANSHAJB10 is already working on this! Feel free to take a look at the other tasks or suggest something!
