### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by PravinPadalkar78** [avincodes/portfolio#21]
Contributing file is missing in your repository and it is useful for the people who don't know how to contribute

If you find this useful please assign this to me

**Comment by avincodes** [comment]
Sure go for it @PravinPadalkar78!

**Comment by PravinPadalkar78** [comment]
can u please assign and lable me

**Comment by avincodes** [comment]
Sure, the label in the PR is what counts tho!

**Comment by PravinPadalkar78** [comment]
oh I didn't know that

**Comment by avincodes** [comment]
Well, now you know! 😅

**Comment by PravinPadalkar78** [comment]
Yeh😅

**Comment by namit343** [comment]
Hello, please assign me this and thanks!

**Comment by avincodes** [comment]
Sure! Done @namit343
