### ISSUE TITLE
feat: Add prettier config file

### ISSUE THREAD

**Issue by akshitarora921** [avincodes/portfolio#27]
Add prettier config for better code formatting and less unwanted code formatting changes in the PRs.

**Comment by avincodes** [comment]
@akshitarora921 I can't quite understand what you are referring to! Could you please elaborate?

**Comment by akshitarora921** [comment]
Reference [link](https://prettier.io/)

**Comment by IvySaskia** [comment]
May I do this issue? @akshitarora921 
:)

**Comment by akshitarora921** [comment]
Hi @IvySaskia,
Thank you for showing your interest. This issue is not yet confirmed by @avincodes, you can take this if/when it is confirmed.
Happy Coding

**Comment by akshitarora921** [comment]
@avincodes Thank you for the confirmation. You can assign this to @IvySaskia

**Comment by avincodes** [comment]
Thank you, appreciate the kind gesture! @akshitarora921

**Comment by avincodes** [comment]
@IvySaskia you can go for it! 🙌

**Comment by IvySaskia** [comment]
Thaks, working on that now. :)

**Comment by avincodes** [comment]
Sure, PR it when ready! I'll be around!

**Comment by avincodes** [comment]
@IvySaskia any update?

**Comment by akshitarora921** [comment]
@avincodes As there is no update from @IvySaskia. Please assign this issue to me.

**Comment by avincodes** [comment]
@akshitarora921 would you like to still take up this issue?

**Comment by akshitarora921** [comment]
sure, @avincodes will do it

**Comment by avincodes** [comment]
Perfect! Assigned!

**Comment by akshitarora921** [comment]
@avincodes Please review the PR.
