### ISSUE TITLE
Change Content 

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#3]
The task attached to this issue is to change some content on the second section of the home page shown below, the new content has also been attached below.

![image](https://user-images.githubusercontent.com/66766682/193451861-66d0a07a-5366-42d3-83e9-9ac226cb4f90.png)
Please change the text "@pissukanna(2022)" to "@Github Campus Expert" make the word GitHub purple and link it to [this](https://education.github.com/experts) page. And finally please replace the image with the following file. 
![image](https://user-images.githubusercontent.com/66766682/193451946-c44f222c-8cb0-4c4a-8224-008b5205a49e.png)

_Please comment below and assign this to yourself before starting to work on it._

**Comment by parulgupta26** [comment]
Hey @avincodes I can help. Kindly assign to me.

**Comment by avincodes** [comment]
Hi, @parulgupta26 unfortunately someone else has already started working on this! Sorry about that, but feel free to look at the other issues as well as any suggestions you have!

**Comment by avincodes** [comment]
@parulgupta26 you can go for this!

**Comment by VidishaAG** [comment]
If this is still open, I want to work on this.

**Comment by avincodes** [comment]
@parulgupta26 this issue has been reassigned to @VidishaAG due to inactivity!

**Comment by avincodes** [comment]
@VidishaAG any update?

**Comment by VidishaAG** [comment]
@avincodes I am having some problems setting up the project. I am unable to set up Vue.
<img width="1440" alt="Screenshot 2022-10-11 at 4 40 41 PM" src="https://user-images.githubusercontent.com/96626537/195116692-659d7614-9842-4f7a-8b51-64c5b1399573.png">

**Comment by VidishaAG** [comment]
@avincodes I am facing some problems setting up Vue.
<img width="1440" alt="Screenshot 2022-10-11 at 7 50 20 PM" src="https://user-images.githubusercontent.com/96626537/195117112-dd54ac69-2728-4c54-a8fa-b83127b48681.png">

**Comment by avincodes** [comment]
@VidishaAG shall I reassign this?

**Comment by VidishaAG** [comment]
> @VidishaAG shall I reassign this?

Yes you may.

**Comment by avincodes** [comment]
@parulgupta26 can you do this?

**Comment by avincodes** [comment]
@parulgupta26 are you still interested in trying this?
