### ISSUE TITLE
Chore: Update dependencies and make it easier to run in a local environment

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#36]
**This webpage currently requires Visual Studio developer tools to run in a local environment, making it difficult for contributors to get started and develop on the project.**

We would like to address this issue by updating our dependencies and making the webpage easier to run in a local environment. This could involve:

- Updating the dependencies to the latest versions.
- Removing any unnecessary dependencies.
- Making sure that the webpage can be run without Visual Studio developer tools.
- Cleaning up the npm files and making them more organized.
Once these tasks are completed, it will be much easier for contributors to get started and develop on the project.

Steps to reproduce:

- Clone the repository.
- Install the dependencies.
- Try to locally run the webpage.

Expected behavior:

- The webpage should be easy to deploy and test in a local environment without Visual Studio Developer Tools.

Actual behavior:

- The webpage requires Visual Studio developer tools to run.

Acceptance criteria:

- The webpage can be run without Visual Studio developer tools.
- All dependencies are updated to the latest versions. (optional)
- All unnecessary dependencies are removed.
 
Please get yourself assigned before starting to work on the issue.

**Comment by priyankaborwanker** [comment]
I would like to contribute to this @avincodes

**Comment by Ritish134** [comment]
Hi there would like to work on this issue can you please assign me

**Comment by avincodes** [comment]
yes, done!

**Comment by bhishekprajapati** [comment]
Hey @avincodes, 
I've managed to get the project running locally. I've made the local development easier.
I've fixed this issue and also found out a few more issues that needs to be fixed.

can you assign me?

**Comment by avincodes** [comment]
Hey @bhishekprajapati unfortunately someone is already working on this issue, however since you have already fixed the issue, can you open a PR and I'll be able to take a look! Thanks!

**Comment by bhishekprajapati** [comment]
I'll open a PR!

**Comment by bhishekprajapati** [comment]
Hey @avincodes, I've commit my changes and opened a PR.

[PR](https://github.com/avincodes/portfolio/pull/40)
