### ISSUE TITLE
Change Color Pallete

### ISSUE THREAD

**Issue by avincodes** [avincodes/portfolio#6]
Currently, the main color tones of the website are black and dark purple, the task related to this issue is to change the purple accents to dark red. 

_Please assign this to yourself before you start working on it_

**Comment by aishwarya1735** [comment]
Can this issue be assigned to me ?

**Comment by avincodes** [comment]
Yes! Go for it!

**Comment by avincodes** [comment]
@aishwarya1735 any update on this?

**Comment by Suraj-Bhandarkar-S** [comment]
If this is open I would like to take a look into this

**Comment by VidishaAG** [comment]
Can i be assigned please? I want to work on this.

**Comment by avincodes** [comment]
@aishwarya1735 this issue has been assigned to @Suraj-Bhandarkar-S due to inactivity.

**Comment by avincodes** [comment]
Sorry, @VidishaAG I just assigned it! :/ Do feel free to check out the other issues and recommend any suggestions tho!
